[build-system]
requires = ["setuptools>=61;python_version>='3'", "setuptools_scm[toml]>8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = ["scVAEIT"]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "mypackage.__version__"}